#q1: this is to set seed. By doing so, the initiation point is always the same, not random.
set.seed(2) 
# assign the value 30 to the variable "sampleSize"
sampleSize <- 30
#q2: randomly generate 20000 numbers that obeyed normal distribution with mean 20 and standard deviation 3. 
# Then assign those numbers to the vector "studentPop".
studentPop <- rnorm(20000,mean=20,sd=3)
studentPop

undergrads <- sample(studentPop,size=sampleSize,replace=TRUE)
mean(undergrads)

#q4: create a sample of graduate students--randomly generate 30 numbers (use sampleSize) that obeyed normal distribution with mean 25 and sd 3. See the mean is 5 years older than the undergraduate sample apparently.  
# Assign the numbers to the vector "grads".
# Sample size is sampleSize (==30), mean is 25, standard deviation is 3. 
grads <- rnorm(sampleSize,mean=25,sd=3)
#q5: Randomly assign either the grads sample or the undergrads sample to testSample, depending on the value generated by runif(1).
# "runif(1)" would generate a random number between 0 and 1. 
# If the number is greater than 0.5, assign grads sample to testSample. Otherwise, assign undergrads sample to testSample.

if (runif(1)>0.5) { testSample <- grads } else { testSample <- undergrads }
mean(testSample)

mean(testSample)
mySample <- replicate(100, mean(sample(studentPop, size =5),replace =T),simplify = T)
quantile(mySample)

mean(testSample)
mean(mySample)
quantile(testSample, c(0.025,0.975))
quantile(mySample, c(0.025,0.975))
